FROM centos:latest
MAINTAINER Syed Mohammed
RUN sudo yum update
RUN sudo yum install -y mysql-server
RUN sudo yum install -y git
RUN mkdir -p /usr/local/mysqlcontainer/
RUN git clone https://github.com/kuthubshavali/MySQLRepo.git
RUN mv PythonDock /usr/local/mysqlcontainer/

